config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'

  post 'foods/:id/bought' => 'foods#bought'
  patch 'foods/:id/bought' => 'foods#update'

  resources :cabinets
  resources :foods
  resources :lists
    

end

app/models/cabinet.rb
class Cabinet < ActiveRecord::Base
	has_many :foods, dependent: :destroy
	belongs_to :kitchen
	validates :name, presence: true

end

app/models/food.rb
class Food < ActiveRecord::Base
	belongs_to :cabinet
	belongs_to :list
	validates :name, presence: true 
end

app/models/kitchen.rb
class Kitchen < ActiveRecord::Base
	has_many :cabinets, dependent: :destroy
	validates :name, presence: true
end

app/models/list.rb
class List < ActiveRecord::Base
	has_many :foods, dependent: :destroy
	belongs_to :kitchen
	validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cabinets_controller.rb
class CabinetsController < ApplicationController
	def index
		@cabinets = Cabinet.all
	end

	def show
		@cabinet = Cabinet.find(params[:id])
		@foods = @cabinet.foods
	end

	def new
		@cabinet = Cabinet.new
	end

	def edit
		@cabinet = Cabinet.find(params[:id])
	end

	def create
		@cabinet = Cabinet.new(cabinet_params)
		if @cabinet.save
			redirect_to cabinets_path
		else
			render 'show'
		end
	end

	def update
		@cabinet = Cabinet.find(params[:id])
		@cabinet.update(cabinet_params)

		redirect_to cabinets_path
	end

	def destroy
		@cabinet = Cabinet.find(params[:id])
		@cabinet.destroy

		redirect_to cabinets_path
	end

	private
		def cabinet_params
			params.require(:cabinet).permit(:name)
		end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
	def index
		@foods = Food.all
		if params[:edit] == true
			@food = Food.find(params[:id])
		end
	end

	def new
		@food = Food.new
	end

	def edit
		@food = Food.find(params[:id])
		@foods = Food.all
		render 'index' # Requires a reload to get button to work
	end

	def create
		if params[:type] == 'cabinet'
			@cabinet = Cabinet.find(params[:parent_id])
			@food = @cabinet.foods.new(food_params)
			@food.save

			redirect_to cabinet_path(@food.cabinet)
		elsif params[:type] == 'list'
			@list = List.find(params[:parent_id])
			@food = @list.foods.new(food_params)
			@food.save

			redirect_to list_path(@food.list)
		else 
			redirect_to cabinets_path
		end
	end

	def update
		@food = Food.find(params[:food_id])
		# if @food.update(food_params)
		
		cabinet = Cabinet.find(params[:cabinet_id])
		@food.update(cabinet: cabinet, list: nil)
		# @food.cabinet = Cabinet.find(params[:cabinet_id])

		redirect_to cabinet_path(cabinet)
		# elsif @food.list
		# 	redirect_to list_path(@food.list)
		# else
		# 	redirect_to cabinets_path
		# end
		# else 


		
	end

	def destroy
		begin
			@cabinet = Cabinet.find(params[:cabinet_id]) || nil
			@food = Food.find(params[:id])
			@food.destroy
			redirect_to cabinet_path(@cabinet)
		rescue 
			@food = Food.find(params[:id])
			@food.destroy
			redirect_to cabinets_path
		end
	end

	def bought
		@food = Food.find(params[:food_id])
		@cabinets = Cabinet.all
	end

	private
		def food_params
			params.require(:food).permit(:name, :quantity, :weight)
		end
		def food_params_update
			params.require(:food).permit(:cabinet)
		end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
	def index
		@lists = List.all
	end

	def show
		@list = List.find(params[:id])
		@foods = Food.all
	end

	def new 
		@list = List.new
	end 

	def destroy
		@list = List.find(params[:id])
		@list.destroy
		redirect_to lists_path
	end

	def create
		@list = List.new(cabinet_params)
		if @list.save
			redirect_to list_path(@list)
		else 
			redirect_to lists_path
		end
	end

	private
		def cabinet_params
			params.require(:list).permit(:name)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cabinet_helper.rb
module CabinetHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/grocery_list_helper.rb
module GroceryListHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/cabinets/_new.html.erb
<%= form_for(:cabinet, url: '/cabinets') do |f| %>
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/cabinets/edit.html.erb
<%= form_for @cabinet do |f| %>
	<p>
		Old Name: <%= @cabinet.name %>
	</p>
	<p>
		New Name: <%= f.text_field :name %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/cabinets/index.html.erb
<h1>All Cabinets</h1>


<table>
	<tr>
		<th>Name</th>
		<th colspan='2'></th>
	</tr>
	<% @cabinets.each do |cabinet| %>
		<tr>
			<td>
				<%= link_to cabinet.name, cabinet_path(cabinet) %>
			</td>
			<td>
				<%= link_to "Edit", edit_cabinet_path(cabinet) %>
			<td>
				<%= link_to "Delete", cabinet_path(cabinet), method: 
					'delete', data: {confirm: 'Are you sure?'} %>
			</td>
		</tr>
	<% end %>
</table>

<br>
<h2>Add a Cabinet</h2>
<%= render "new" %>

<br>
<%= button_to "Show All Food", foods_path, method: :get %>
<h3><%= link_to 'See All Lists', lists_path %></h3>

app/views/cabinets/show.html.erb
<h1><%= @cabinet.name %></h1>

<table>
	<tr>
		<th>Quantity</th>
		<th>Name</th>
		<th>Weight (g)</th>
		<th colspan='2'></th>
	</tr>
	<% @foods.each do |food| %>
		<tr>
			<td><%= food.quantity %></td>
			<td><%= food.name %></td>
			<td><%= food.weight %></td>

			<td>
				<%= link_to "Edit", edit_food_path(food) %>
			<td>
				<%= link_to "Delete", food_path(food) + "?cabinet_id=" + params[:id], method: 
					:delete, data: {confirm: 'Are you sure?'} %>
			</td>
		</tr>
	<% end %>
</table>

<br>
<% params[:type] = 'cabinet' %>
<%= render 'foods/new' %>

<br>
<h3><%= link_to "Back to Cabinets", cabinets_path %> | <%= link_to "See All Lists", lists_path %></h3>

app/views/foods/_food_table.html.erb
<table>
	<tr>
		<th>Quantity</th>
		<th>Name</th>
		<th>Weight (g)</th>
		<th>Cabinet</th>
		<th colspan='3'></th>
	</tr>
	<% @foods.each do |food| %>
		<% if @food && @food == food %>
			<tr>
				<%= form_for(:food, url: '/foods/' + food.id.to_s, 
					method: 'patch') do |f| %>
				<td><%= f.text_field :quantity %></td>
				<td><%= f.text_field :name %></td>
				<td><%= f.text_field :weight %></td>
				<td></td>
				<td>
				</td>
				<td>
					<%= link_to "Delete", food_path(food) + "?cabinet_id=" + food.cabinet_id.to_s, method: 
						:delete, data: {confirm: 'Are you sure?'} %>
				</td>
				<td><%= f.submit %></td>
				<% end %>
			</tr>
		<% else %>
			<tr>
				<td><%= food.quantity %></td>
				<td><%= food.name %></td>
				<td><%= food.weight %></td>
				<% if food.cabinet %>
					<td><%= food.cabinet.name %></td>
				<% elsif food.list %> 
					<td>For debugging: <%= food.list.name %></td>
				<% else %>
					<td></td>
				<% end %>

				<td>
					<%= link_to "Edit", edit_food_path(food) %>
				</td>
				<td>
					<%= link_to "Delete", food_path(food) + "?cabinet_id=" + food.cabinet_id.to_s, method: 
						:delete, data: {confirm: 'Are you sure?'} %>
				</td>
			</tr>
		<% end %>
	<% end %>
</table>

app/views/foods/_new.html.erb
<h3>Add a Food</h3>

<!%= form_for(:food, url: ('/foods?parent_id=' + params[:id]), method: :post ) do |f| %>
<%= form_for(:food, url: {controller: 'foods', parent_id: params[:id], type: params[:type]}, method: :post ) do |f| %>
	<table>
		<tr>
			<td>Name: </td>
			<td><%= f.text_field :name %></td>
		</tr>
		<tr>
			<td>Quantity:</td>
			<td><%= f.text_field :quantity %></td>
		</tr>
		<tr>
			<td>Weight (g): </td>
			<td><%= f.text_field :weight %></td>
		</tr>
		<% if @list %>
			<!-- <tr>
				<td>List: </td>
				<td><%= f.text_field :list, value: @list.name %></td>
			</tr> -->
		<% end %>	
	</table>

	<% if @food && @food.errors.any? %>
		<p>Food must have a name</p>
	<% end %>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/foods/bought.html.erb
<h2><%= @food.name %></h2>

<% @food.list = nil %>

<%= form_for @food , url: { food_id: @food} do |f| %>
	<p>Transfer to Cabinet:</p> 
	<p>	
		<% @cabinets.each do |cabinet| %>
			<%= radio_button_tag(:cabinet_id, cabinet.id) %>
			<%= label :cabinet_name, cabinet.name %>
			<br>
		<% end %>
	</p>
	<p><%= f.submit %></p>
<% end %>

app/views/foods/edit.html.erb
<%= form_for @food do |f| %>
	<table>
		<tr>
			<th></th>
			<th>Old</th>
			<th>New</th>
		</tr>
		<tr>
			<td>Name:</td>
			<td><%= @food.name %></td>
			<td><%= f.text_field :name %></td>
		</tr>
		<tr>
			<td>Quantity:</td>
			<td><%= @food.quantity %></td>
			<td><%= f.text_field :quantity %></td>
		</tr>
		<tr>
			<td>Weight:</td>
			<td><%= @food.weight %></td>
			<td><%= f.text_field :weight %></td>
		</tr>
	</table>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/foods/index.html.erb
<h1>All Food</h1>

<%= render 'food_table' %>
<br>

<h3><%= link_to 'See All Cabinets', cabinets_path %> | <%= link_to 'See All Lists', lists_path %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>SmartKitchen</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/lists/_form.html.erb
<h2>Create New List</h2>

<%= form_for :list do |f| %>
	<p>Name: <%= f.text_field :name %></p>
	<p><%= f.submit %></p>
<% end %>

app/views/lists/index.html.erb
<h1> All Lists</h1>

<table>
	<tr>
		<th>Name</th>
		<th colspan="2"></th>
	</tr>
	<% @lists.each do |list| %>
		<tr>
			<td><%= link_to list.name, list_path(list) %></td>
			<td><%= link_to 'Edit', edit_list_path(list) %></td>
			<td><%= link_to 'Delete', list_path(list), method: :delete, data: {confirm: 'Are you sure?'} %></td>
		</tr>
	<% end %>
</table>	

<br>
<%= render 'form' %>

<br>
<%= button_to 'See All Foods', foods_path, method: :get %> 
<h3><%= link_to 'See All Cabinets', cabinets_path %></h3>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<table>
	<tr>
		<th>Quantity</th>
		<th>Name</th>
		<th colspan="3"></th>
	</tr>
	<% @foods.each do |food| %>
		<% if food.list == @list %>
			<tr>
				<td><%= food.quantity %></td>
				<td><%= food.name %></td>
				<td><%= link_to 'Edit', edit_food_path(food) %></td>
				<td>
					<%= link_to 'Delete', food_path(food), 
					method: :delete, data: {confirm: 'Are you sure?'} %>
				</td>
				<td>
					<%= button_to 'Bought', controller: 'foods', action: 'bought', food_id: food.id %>
				</td>
			</tr>
		<% end %>
	<% end %>
</table>

<br>
<% params[:type] = 'list' %>
<%= render 'foods/new' %>

<br>
<h3><%= link_to 'Back to Lists', lists_path %> | <%= link_to 'See All Cabinets', cabinets_path %></h3>